[package]
name = "potanist"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"

[lib]
crate-type=["cdylib"]
