use phf::phf_map;

pub static POKEMON_NATURES: phf::Map<u8, (&'static str, &'static str)> = phf_map! {
    0u8 => ("Hardy", "がんばりや"),
    1u8 => ("Lonely", "さみしがり"),
    2u8 => ("Brave", "ゆうかん"),
    3u8 => ("Adamant", "いじっぱり"),
    4u8 => ("Naughty", "やんちゃ"),
    5u8 => ("Bold", "ずぶとい"),
    6u8 => ("Docile", "すなお"),
    7u8 => ("Relaxed", "のんき"),
    8u8 => ("Impish", "わんぱく"),
    9u8 => ("Lax", "のうてんき"),
    10u8 => ("Timid", "おくびょう"),
    11u8 => ("Hasty", "せっかち"),
    12u8 => ("Serious", "まじめ"),
    13u8 => ("Jolly", "ようき"),
    14u8 => ("Naive", "むじゃき"),
    15u8 => ("Modest", "ひかえめ"),
    16u8 => ("Mild", "おっとり"),
    17u8 => ("Quiet", "れいせい"),
    18u8 => ("Bashful", "てれや"),
    19u8 => ("Rash", "うっかりや"),
    20u8 => ("Calm", "おだやか"),
    21u8 => ("Gentle", "おとなしい"),
    22u8 => ("Sassy", "なまいき"),
    23u8 => ("Careful", "しんちょう"),
    24u8 => ("Quirky", "きまぐれ"),
};
